### PR TITLE
Moved tests

### PR DESCRIPTION
**Pull request by ghost**
Moved tests to a different directory, which cleans up `/src/` a bit.
Sorry about the branch name :/

### CODE REVIEW

**Comment by ghost** [comment]
Sorry about the weird commits thing too, if it's a problem I can google how to fix it.

**Comment by pakastin** [comment]
Maybe it's better to do another pull request from scratch, since there's not much happening here – right?

**Comment by ghost** [comment]
Yeah, tried to rewrite my email because GitHub complains about that. Hang on.

**Comment by ghost** [comment]
Sorry about the long wait. I've ended up just manually copying the changes to another branch to get around this.

**Pull request closed without merging**
