### PR TITLE
Added an npmignore

### PR DESCRIPTION
**Pull request by ghost**
Added an npmignore, which should skim time off downloading teston from npm

### CODE REVIEW

**Comment by pakastin** [comment]
Whoops, `src` is the module itself when you’re using es6 modules, so can’t ignore that 😬

**Comment by pakastin** [comment]
It’s defined here: 
https://github.com/pakastin/teston/blob/master/package.json#L6

**Comment by ghost** [comment]
Yeah, but you should provide an already built version when distributing. I'll push another commit that'll support building to the `es` format.

**Comment by pakastin** [comment]
It's actually better to have separate files, because you can import only certain files and tree shaking is easier, too.. Not recommended to prebundle ES6 modules.

**Comment by ghost** [comment]
That's why you separate tests from `src`. Might have to merge `added-tests` into this :/

**Comment by pakastin** [comment]
Yeah, I agree it's a good idea to separate tests.

**Comment by ghost** [comment]
Like it?

**Comment by pakastin** [comment]
Didn’t actually know (or remember) about `npmignore`. That’s really useful! 👌

**Comment by ghost** [comment]
Glad all these PRs are helpful. I'll be sure to send in more PRs when I see something wrong.

**Pull request merged**
