### PR TITLE
Changed readme

### PR DESCRIPTION
**Pull request by ghost**
Added a bit better api documentation, and made markdown-lint less angry, so that's a good thing.

### CODE REVIEW

**Comment by pakastin** [comment]
Looking good, thank you so much! 🙂👍

**Comment by ghost** [comment]
lol hope i helped with all these prs, happy to lend a hand. ps when is the stable v1 out, not happy to use this when the api is shaky

**Comment by ghost** [comment]
another thing, wondering about integration with Babel? basically I'm using es6 modules and mocha has a `--require` flag for transpilers, just wondering if I need to manually code in a build task, then point teston to it

**Comment by pakastin** [comment]
Basically it’s already v1 in a sense that I’m not breaking the current syntax. I’ve used tape for a long time and having even simpler syntax is just what I want (only `t(` for subtests).

Only thing keeping at `0.x` is just testing everything work like expected, maybe also adding a little website, finishing things up etc..

**Comment by pakastin** [comment]
I don’t see babel as relevant anymore here. Of course it’s still good practise to bundle and support legacy browsers, but what comes to unit testing, it’s nice to just test the original code as is.

However nothing prevents adding a simple wrapper for babel/rollup 🤷‍♂️

**Pull request merged**
